### ISSUE TITLE
2023 Roadmap Planning

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-gui#102]
Roadmap planning is being done [publicly here](https://pl-strflt.notion.site/IPFS-GUI-Tools-Roadmap-19463391b52144caabc053888c58ddbb). ([Link to same page that requires a Notion account](https://www.notion.so/pl-strflt/IPFS-GUI-Tools-Roadmap-19463391b52144caabc053888c58ddbb))

Please comment on the doc or comment on this issue here if you have questions/comments on our plan for 2023.

**Comment by tinytb** [comment]
(updated the original post)

**Comment by SgtPooki** [comment]
The roadmap is being created at https://github.com/ipfs/ipfs-gui/issues/106 now, I will be moving over data from notion into issues and linking things

**Comment by SgtPooki** [comment]
Please use #106 for comments on our roadmap. closing this issue
