### ISSUE TITLE
Create and document process for generating all-hands reports

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-gui#126]
generate an easy-to-consume report we can present at our weekly All-Hands meetings.

- [x] Generate a report that consolidates the data from all of our projects (see #105)
- [ ] Define process for building report and adding to allhands slides

## Questions we will answer with Metrics

Data to provide in the generated report

Note that we can potentially get aggregated data across all projects using app consolidation: https://support.count.ly/hc/en-us/articles/900004464043-Consolidate

#### Not including users who opt-out

1. How many daily/weekly/monthly active users(unique) does <project> have?
1. How long do users typically keep <project> open when using it? (session length/duration)
1. What is the WoW/MoM trend of user session times in <project>?
1. What are the most viewed pages within <project>?
1. What is the WoW/MoM trend of active users(unique) for <project>?
1. Error count on the frontend (optional)
2. Performance metrics (optional)

#### Including users who opt-out or do not upgrade.

1. What is the size of the total users of <project>? (we will know the answer here because a single event is sent informing us that a user has opted out of metrics)
    - How many users benefit from our products?
3. How many open issues do we have as a team? (see https://github.com/SgtPooki/github-issue-stats)
4. What is the lead time from issue open to issue close? (see https://github.com/SgtPooki/github-issue-stats)

#### Other data that is not confirmed to be possible, but is desired

1. How many daily/weekly/monthly active users(unique) are there across all <project>s?
1. What is the total WoW/MoM trend of active users across all <project>s?

**Comment by tinytb** [comment]
Some ideas for product-specific questions (thanks @whizzzkid) --

gateway-checker (Can this benefit as a tool for everyone including local gateways?)
- total time to resolve all gateways.
- missing flags
- frequently down gateways.

companion (Impact on user browsing? do we slow them? do we provide an easy transition to ipfs?)
- number of urls intercepted.
- number of urls served.
- number of urls recovered using public gateway.
- average time to resolve (slow gateways)
- version, (lead time to upgrade)

desktop (is the UI adding value and providing users meaningful ways to interact with IPFS?)
- front end errors
- heatmap
- popular section
- background session length
- number of consecutive clicks (we can maybe use this to reduce clicks to perform actions)

**Comment by SgtPooki** [comment]
Note that our metrics dashboard page is created, though still in progress, at https://pl-strflt.notion.site/IPFS-Ignite-Metrics-Dashboard-dee2ada6225e4e01a172673496851210

**Comment by SgtPooki** [comment]
This issue is useful for historical purposes and tracking metrics/data we may want to add/report on moving forward, but for the sake of the "telemetry project" from the Ignite team, this issue will be closed once https://github.com/ipfs-shipyard/ignite-metrics/pull/86 is merged.

**Comment by SgtPooki** [comment]
In addition to the count of intercepted URLs, here are some ipfs-companion metrics I've been thinking would be nice:

* how many users are connected to an ipfs node vs disconnected?
* how long are users disconnected from an ipfs node? (And how many polling requests have we sent?)
* how many users have brave/external/gateway selected as their node of preference?
