### ISSUE TITLE
Discussion: Metrics normalization 

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-gui#128]
ipfs-companion metrics from firefox does not support monthly active users. We need a way to normalize them. 
   * metrics not available at https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/statistics/usage already are not supported by firefox addons without a change here and other places: https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/cron.py

This issue should cover any other projects that don't use the same metrics collection system as the rest of our projects (currently using countly).

Some questions and other considerations:

1. Do we want to add countly metrics collection to ipfs-companion? 
2. Is adding additional metrics (countly) collection in ipfs-companion going to work?

Proposed answers:

1. Yes, this would ensure all our projects have normalized metrics and aren't dependent upon different tools
2. needs investigation

**Comment by BigLep** [comment]
I think it's useful to be able to own our metrics so we can more confidently reason them, and so we have to put less trust in other groups.

That said, if this becomes a major undertaking, I am fine not prioritizing it right now.  

For example, while yes it would be nice if Firefox Companion gave different stats than daily active users, Firefox companion usage is also the smaller piece of the pie and is less critical to me.

**Comment by SgtPooki** [comment]
closing this. See https://github.com/ipfs/ipfs-gui/issues/125 and https://github.com/ipfs/ipfs-gui/issues/105
