### ISSUE TITLE
What is the ipfs font?

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#22]
it would be good to have a font that can be used for fancy headers across ipfs-companion, ipfs-desktop and ipfs-dashboard, and any other ipfs apps. 

https://ipfs.io currently uses Brandon Text - https://www.myfonts.com/fonts/hvdfonts/brandon-text/

<img width="551" alt="screenshot 2018-01-09 10 36 16" src="https://user-images.githubusercontent.com/58871/34716833-f7091092-f528-11e7-9f08-8f3ee30f1ba1.png">

Who is the license holder for the copy that is [currently used on ipfs.io](https://github.com/ipfs/website/blob/22beb24497a162cfc6ab42e2f461df0060b9e0ca/less/components/typography.less#L8-L36)? 

The license is here: http://www.myfonts.com/viewlicense?type=web&buildid=3229221

The license seems pretty standard, but somewhat restrictive:

> Use of the Licensed Web Fonts with technologies other than @font-face, such as sIFR, Cufón or Typeface.js, is not allowed. 

> You must retain the page view tracking code, as supplied in the Web Font Kit, on all Websites that Use the Licensed Web Fonts. 

> The Licensed Web Fonts may be used on any Website owned or controlled by you (subject to the next bullet point). The total traffic, measured in page views, of all Websites Using a Licensed Web Font must be no greater than the number of page views specified in your account at located at www.myfonts.com

At time of purchase, it seems that ` number of page views specified in your account` was [set 10,000 / per month](https://github.com/ipfs/website/blob/22beb24497a162cfc6ab42e2f461df0060b9e0ca/less/components/typography.less#L38-L39)

Settling on a more permissively licensed font would be great.

**Comment by olizilla** [comment]
@akrych aside from license issues, will you be reviewing the ipfs fonts as part of the new brand guide work?

**Comment by akrych** [comment]
`@akrych aside from license issues, will you be reviewing the ipfs fonts as part of the new brand guide work?`

@olizilla Yes :) 👍 

Made some "table of contents" plan:

Introduction 

1. What is IPFS? 
2. The brand essence 

Logo 

1. Orgins of logo 
2. Construction 
3. The variations 
4. Monochrome variations 
5. Color variations 
6. Logo on backgrounds 
7. Clear space of logo 
8. Minimal size 
9. Prohibited use 
10. Use on backgrounds

Visual identity

1. Colors
2. Typography
3. Icons
4. Illustrations

Let me know if you want to add something :)

**Comment by olizilla** [comment]
@akrych thats good to know. thanks! That's a good list, I've nothing to add. We can grow it over time. What format are you thinking of publishing it as? I'd be happy to help build out as a website so people can link to it.

**Comment by akrych** [comment]
@olizilla The first thing is to have a "book" - I mean made in inDesign *.PDF file. And I think here about 2 documents - biger (full brand book) and smaller (handy version to download from page). Ideally, if we would also have a guideline website on IPFS subpage with some basic info about logo/identity.

**Comment by olizilla** [comment]
Just a thought, but I feel like the ipfs crowd is a "web first" kinda crew. I might be worth thinking about the brand book as a website from the start.

**Comment by akrych** [comment]
@olizilla - Sure, we just need to know if we have enough people/time/etc to do it :D but yeah, sure!

**Comment by LinusEkenstam** [comment]
Hey @akrych and @olizilla - I'd love to help out in what ever way I can. Let me know what you need a hand with.

**Comment by akrych** [comment]
@olizilla  - What do you think about change "Brandon Text" to "Montserrat" font? https://github.com/JulietaUla/Montserrat 

![new_font](https://user-images.githubusercontent.com/22168118/34790635-9cc94348-f642-11e7-9050-1653643155e5.png)

**Comment by olizilla** [comment]
I like it for use in headers and hero sections, and I like that it's open licensed. I'm mildly against using it for main copy. 

Coming from a web dev background, I have a strong bias for using the whatever the users current os system font is for longer sections of text; it avoids the layout jiggling around when as the custom web font loads, and is generally optimised for legibility at all sizes, and feels familiar by blending in with the OS interface.

 Do you have any others in the short list?

**Comment by akrych** [comment]
Sure, we can just add safe web font - maybe Verdana? It pair pretty good with "Montserrat" font

![new_font](https://user-images.githubusercontent.com/22168118/34821814-3086e482-f6c5-11e7-86a0-c494012cc6c4.png)

**Comment by olizilla** [comment]
As a data point for the current situation, ipfs-deskopt is currently using the "Inter UI" font family - https://github.com/rsms/inter

**Comment by LinusEkenstam** [comment]
@olizilla - I think Rasmus has done an incredible job with Inter, and if possible you should stick with it. It's pure typeface love.

**Comment by ericronne** [comment]
@akrych / @olizilla is this closable? 
(note: we may take another look at brand typography down the road)

**Comment by jessicaschilling** [comment]
Closing for now -- we'll be examining typefaces as a whole as part of reworking ipfs.io (and a parent branding effort as a whole), hopefully later this year.
