### ISSUE TITLE
Available to help out. 

### ISSUE THREAD

**Issue by LinusEkenstam** [ipfs/ipfs-gui#23]
Hey guys! I'm me, and I would like to help out with whatever needs an extra pari of designer eyes. 

My background is more or less 10 years of UI/UX working on everything from marketing websites to bigger products. My last job was at https://typeform.com and now I'm working with a little bit of everything. I was involved a bit with Filecoin and Coinlist some months back too. 

The past year I've been focused more on building design systems, and figuring out good ways for that to work at scale. But also working with more gritty product design work as well as marketing sites. 

You can see some of my projects here: http://linusekenstam.com - Or just ask some questions and I'd be happy to try to answer them and give more info. 

/ L

**Comment by olizilla** [comment]
Nice to meet you @LinusEkenstam! 

It's early days for the ipfs-gui team, so we're still setting up and figuring out responsibilities, so it might be a little while before we have anything concrete to point you at, but we will! There is plenty to do.

I'd love to chat about design systems and I'd like https://github.com/ipfs-shipyard/ipfs-ui-style-guide to grow into that for ipfs.

**Comment by LinusEkenstam** [comment]
@olizilla - Nice, I've been part of building the design system over at Typeform.com and Karri one of the guys behind the AirBnb Design Language System is a friend of mine. Let me know if you have concrete questions or just want to have a face to face video chat at some point, would love to be able to contribute. :-)

**Comment by VictorBjelkholm** [comment]
@LinusEkenstam if you're still interested, browse through the new issues that have been created in this repository recently, might find something interesting to help out with :)

https://github.com/ipfs-shipyard/pm-ipfs-gui/issues

**Comment by LinusEkenstam** [comment]
@VictorBjelkholm - I am still interested, just have been very very very short on time. I'm looking through to see if there is something I can assist with.

**Comment by olizilla** [comment]
@LinusEkenstam I'm going to be working on defining an open design process for IPFS projects, I'd love your input on that. Do you have any thoughts on what the design equivalent of an "open source" process looks like? How do we design in the open, share our progress and help the community to get involved? What's a healthy, productive version of that look like?

How do we preserve the magic that comes from trusting "the artist in the workshop" to internalise the problem, meditate on it, and create a design direction that finds pleasing balance of trade-offs, but at the same time be open to community contributions and encourage a "PRs welcome" culture, that helps on-board new designers.

Right now we have https://github.com/ipfs-shipyard/pm-ipfs-gui as a first step, to try any explain what we're doing with the webui redsign and why. I'd like to grow the process and the team and the community around it into something much, much brighter!

@akrych @meiqimichelle @andreforsousa I'd love your thought on this too! Right now I'm looking at

- http://opendesignkit.org/ (via https://bocoup.com/blog/open-design-kit-a-toolkit-for-designing-with-distributed-collaborators)
- https://blog.mozilla.org/opendesign/
- https://design.firefox.com/photon/welcome.html

But they don't seem to capture that essence of being able to really collaborate on the finished output in the same way that code can become a shared responsibility and be maintained and improved by a team. A lot of design tooling seems to still be focused on a single design sharing a proprietary artefact (.psd, .sketch etc), even if the entire process that led up to it was fully open an collaborative along the way.

**Comment by jessicaschilling** [comment]
Hi, @linusekenstam! It looks like it's been a while since anyone's touched base with you, so I wanted to do so now 😊 

We're reviving more dedicated work on our overall UX/UI for the family of IPFS helper apps -- IPFS Companion, IPFS WebUI, and IPFS Desktop -- and that would definitely include some work germane to your background, if you're still interested! I'm going to close this issue as part of our overall backlog examination (that's my work over the next few days/weeks), but if you're still game to take part, name-check me in a comment and we'll go from there. Thanks!
