### ISSUE TITLE
Design: Logos / Icons

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-gui#24]
@olizilla asked a very good question during OKR discussion:
> A logo for <del>Dashboard</del>WebUI, Desktop and Companion to give each an identity that shows they separate parts that work together?

**Comment by lidel** [comment]
@olizilla I created design tasks for Companion and Desktop logos, but was not sure about WebUI. 
Feel free to create one if you feel its needed.

**Comment by ericronne** [comment]
@lidel is this closable?

**Comment by lidel** [comment]
Yes, we continue it in https://github.com/protocol/design-shop/issues/95 and https://github.com/protocol/design-shop/issues/96
