### ISSUE TITLE
Design: Generic Landing Page

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-gui#27]
> @akrych  noted that we have various issues related to this, but no "meta-issue" to track progress across all repos, so here it is :)

There is ongoing work that could (potentially) benefit from a common "template":

-  Display a Landing Page on New Installs / Big Updates (https://github.com/ipfs-shipyard/ipfs-companion/issues/324)
-  Check Page for Distributed Web (https://github.com/ipfs/in-web-browsers/issues/61)
- <your project, library that lacks nice landing page/template>

So far we:

- started with initial mockups for a Landing Page at WIP PR https://github.com/ipfs-shipyard/ipfs-companion/pull/326 
- work-in-progress:  [ipfs-ui-style-guide](https://github.com/ipfs-shipyard/ipfs-ui-style-guide) – a shared style guide for UI design in the IPFS universe that extracts common visual features from prior art, builds on top of it and documents everything  in reusable form

Let's keep this ticket open to improve discoverability of related efforts until we have a single template page that follows style guide and can be quickly dropped into projects (eg.  `static-page-demo.html` in [ipfs-ui-style-guide](https://github.com/ipfs-shipyard/ipfs-ui-style-guide) repo?).

**Comment by alanshaw** [comment]
The Dat desktop app has a short onboarding carousel:

![screen shot 2018-03-27 at 15 49 19](https://user-images.githubusercontent.com/152863/38034983-49515224-329b-11e8-9af9-0c768d942457.png)
![screen shot 2018-03-27 at 15 49 31](https://user-images.githubusercontent.com/152863/38034985-49712f72-329b-11e8-8154-6f7a9462c27b.png)
![screen shot 2018-03-27 at 15 49 51](https://user-images.githubusercontent.com/152863/38034986-4988664c-329b-11e8-9442-a0e97c203d94.png)
![screen shot 2018-03-27 at 15 49 57](https://user-images.githubusercontent.com/152863/38034987-49a19356-329b-11e8-9073-0d2adf06fd8f.png)
![screen shot 2018-03-27 at 15 50 07](https://user-images.githubusercontent.com/152863/38034989-49c812f6-329b-11e8-9957-81df43e1bab7.png)
![screen shot 2018-03-27 at 15 50 20](https://user-images.githubusercontent.com/152863/38034990-49df3aee-329b-11e8-9e33-4b8412fbd6fd.png)

**Comment by akrych** [comment]
I like it @alanshaw !

**Comment by jessicaschilling** [comment]
Closing this issue (stale). Please re-open if necessary. Thank you!
