### ISSUE TITLE
Research: The IPFS User Interface Project

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-gui#42]
Just came across the research-project within this repository and came across the following in the first line:

>  want to make IPFS GUIs beautiful, reusable, and unified

Is this not missing the single most important part, `functional` / `easy to use`? It's great that we want to it to be beautiful, but it should be functional and easy for the user foremost.

**Comment by lidel** [comment]
I'll go out on a limb here say that @olizilla simply forgot to put it there up in the front. 
Based on past discussions I am quite sure the _ease of use_ is one of our core goals :)

There is a short "user needs" statement at [research/what-we-want.md](https://github.com/ipfs-shipyard/pm-ipfs-gui/blob/master/research/what-we-want.md).
We do want to provide simple GUI solutions for most common needs. 

Personally, I am all in for making UI _intuitive_. We should simplify complex concepts such as pinning and represent them with well known abstractions. User should not need a manual or support forums to understand what the app does or what is the meaning of a button. Ideally it should be obvious just from looking at UI itself.

**Comment by olizilla** [comment]
STRONGLY AGREE. That line was pulled across from a previous scoping doc. Intuitive / functional / easy-to-use is my goal here. An intuitive user experience is vital. A pleasing, consistent, unsurprising UI design is means for achieving that.

I'll update the research doc.

**Comment by olizilla** [comment]
This has been addressed in the goals section of the updated ipfs-gui project readme:

https://github.com/ipfs/ipfs-gui#goal

> Make the IPFS GUIs simple, accessible, reusable and beautiful.
>
> Simple - Fight complexity at every step. There are big ideas in IPFS. Let's present them clearly.
> Accessible - IPFS must be usable and comprehensible for everyone.
> Reusable - Publish and promote this work. Make doing the right thing the easiest thing.
> Beautiful - Demonstrate the nature of the system with effortless, coherent, and compelling interfaces.

Feel free to reopen this issue if you have a good idea for refining it
