### ISSUE TITLE
Design: IPFS Desktop

### ISSUE THREAD

**Issue by akrych** [ipfs/ipfs-gui#44]
As we agreed earlier we need some design inspirations examples for desktop :) We have some - but I would like to invite you to search some more desktop/file applications that you like.  

It will also extremely useful for me if you point shortly **"what do you like"** and **"what do you don't like"** in specific app/design. The negative examples can be even more useful for design than positive ones :) 👍  

Some examples that we already mention in others issues: 

### Dropbox

<img width="420" alt="screenshot 2018-03-07 10 46 52" src="https://user-images.githubusercontent.com/58871/37089361-2f04835e-21f8-11e8-9e00-969702b0ffca.png">

### Keybase

![screenshot 2018-03-07 10 46 37](https://user-images.githubusercontent.com/58871/37088499-7b4b4de0-21f5-11e8-93d0-e250975d14b2.png)

### Webtorrent

![screenshot 2018-03-07 10 52 15](https://user-images.githubusercontent.com/58871/37089226-c33894d0-21f7-11e8-9841-6fb43a0aea1a.png)

![screenshot 2018-03-07 10 52 20](https://user-images.githubusercontent.com/58871/37089229-c60f1670-21f7-11e8-90ab-f58ceb116590.png)

### Dat desktop

![screenshot 2018-03-07 10 32 21](https://user-images.githubusercontent.com/58871/37089292-f8c3c48a-21f7-11e8-86fa-aa1092e7ce7c.png)

https://github.com/dat-land/dat-desktop#dat-desktop

### Tranmission

<img width="420" alt="screenshot 2018-03-07 10 46 52" src="https://user-images.githubusercontent.com/58871/37089340-1fd67608-21f8-11e8-8e8d-0e5ccba0bf81.png">

### Forever

<img width="1524" alt="screenshot at mar 21 13-48-12" src="https://user-images.githubusercontent.com/22168118/37710766-f0b16208-2d0e-11e8-98e8-e5912420f0ed.png">

https://github.com/ipfs/awesome-ipfs/issues/128

### File Browser by hacdias 
<img width="895" alt="file" src="https://user-images.githubusercontent.com/22168118/37711106-fba97546-2d0f-11e8-9748-023b6d439ffc.png">

https://filebrowser.github.io/

**Comment by lidel** [comment]
## What I like

### Chrome OS file.app

Clean and calm, not much going on (especially in older versions)
- well known abstractions: important directories and foldable tree on left, path-based navigation on the top left, actions on the right top 
- personally, I am not a big fan of foldable directory tree on the left , always keep it folded and prefer to use this space for pinning "bookmarks" to special directories 

![unnamed](https://user-images.githubusercontent.com/157609/37723196-0ca01062-2d2e-11e8-9243-770e56bc3dee.png)
![thumbnails](https://user-images.githubusercontent.com/157609/37721364-907b3790-2d29-11e8-98c9-2043e1f00840.png)

Version with thumbnails may be bit too much tho:

![thumbnails](https://user-images.githubusercontent.com/157609/37721304-710f9a9a-2d29-11e8-9fd8-adfd5a083107.png)

### ownCloud

What i like here is that UI is "faded to background" and what "pops" are your files (if you ignore "enterprisey" banner at the top :sweat_smile:):

![product 2x](https://user-images.githubusercontent.com/157609/37725278-ea4c1786-2d32-11e8-9c07-1bdd312aa59c.png)

## What I did not like

### Bitcasa

![bitcasa-web-interface](https://user-images.githubusercontent.com/157609/37721996-427c8768-2d2b-11e8-8afa-562a19c7bab9.png)

What I did not like:

- sensory overload (tries to be everything at once)
- things feel squeezed together, and at the same time there is a lot of whitespace
- bold design statement that does not play well with window borders of native OS

## Mega.nz

![screen shot 2018-03-21 at 17 43 18](https://user-images.githubusercontent.com/157609/37723735-61a6cbfe-2d2f-11e8-9e3c-b64023a71acc.png)

What I did not like:
- not intuitive: two layers of navigation on the left + item on top + hamburger menu in the right top corner
- unnecessary clutter (eg. wrapping of things like folder icons)

**Comment by olizilla** [comment]
Unradical but worth mentioning. I like OSX finder. Specifically, clean, but not totally minimal. Context menus hide a lot of the work, which may not be appropriate for a web ui version. I use the keyboard navigation and preview function all the time. I dislike multi-pane views, i prefer to focus on one dir at a time but I fear that everyone prefers the file explorer they already know, and that we'll need to offer multiple views.

left-hand side is shortcuts to often used directories, right hand is file list.

![screen shot 2018-03-22 at 10 25 41](https://user-images.githubusercontent.com/58871/37765576-66f6f24a-2dbc-11e8-8df7-d57b8f624221.png)

<img width="812" alt="screen shot 2018-03-22 at 10 25 58" src="https://user-images.githubusercontent.com/58871/37765590-70dda718-2dbc-11e8-9c51-031649140c68.png">

but i don't like

![don-not-want](https://user-images.githubusercontent.com/58871/37766192-1bbae0be-2dbe-11e8-913c-4f275c98ffa1.png)

**Comment by olizilla** [comment]
hang on, this is supposed to be for desktop design... I'm gonna move that preview comment to the file explorer issue.

**Comment by alanshaw** [comment]
![screen shot 2018-03-28 at 15 41 00](https://user-images.githubusercontent.com/152863/38036379-79dd1d30-329e-11e8-85fd-34df167a3298.png)

I like that:

* Leftmost column is the right width to accommodate the macOS close/minimise/maximise circles
* White background for most important content, gradually faded colours as columns become less important/less frequently used
* There's no edge

I don't like:

* Top of main column feels cluttered

**Comment by alanshaw** [comment]
I really like the file icons package for atom: https://github.com/file-icons/atom

<img width="185" alt="screen shot 2018-03-28 at 15 49 01" src="https://user-images.githubusercontent.com/152863/38036933-bc653600-329f-11e8-9e7e-9b87e39ef93a.png">

**Comment by hacdias** [comment]
We're moving the [discussion for IPFS Desktop design](https://github.com/ipfs-shipyard/ipfs-desktop/issues/661) here, so please read the linked issue

This is the current state of what I've done:

| Main Screen | General Settings | Connections |
|-----------------------|-------------------------|---------------------------------|
| ![image](https://user-images.githubusercontent.com/5447088/47148429-9c289e80-d2c8-11e8-9226-b1f30a760079.png) | ![image](https://user-images.githubusercontent.com/5447088/47148435-9fbc2580-d2c8-11e8-8a4e-6bf98879294d.png)| ![image](https://user-images.githubusercontent.com/5447088/47148445-a34fac80-d2c8-11e8-85c4-6aa6a747415a.png) |

**Comment by hacdias** [comment]
Ping @ipfs/gui-team

**Comment by lidel** [comment]
"Main Screen":

- I  feel there should be a decidated button (or icon)  to open "Files"  in Web UI
- Padding looks weird: there is too little of padding around the cube, and too much on the bottom (whitespace)

"General Settings":

- Header should say "Settings" instead of "IPFS Companion"
- "Logs Folder" → "Open Logs" 
- "Quit" – will this also shut down the go-ipfs? 

"Connections" tab:

- I think renaming "Connections" to "Backends" will make things more clear
- (perhaps) rename "Repo Path" to `IPFS_PATH`  (to match environment variable) 
- Those random "pet names" for backends are not user friendly
   - We should at least prefix them with backend  type (eg. "go-NP64Ok_NP")

**Comment by hacdias** [comment]
@lidel great!

> I feel there should be a decidated button (or icon) to open "Files" in Web UI

Yes, and I believe drag'n'drop should also work on desktop.

> Padding looks weird: there is too little of padding around the cube, and too much on the bottom 

I agree: just waiting to know if we're going to change the main screen totally or not.

> Header should say "Settings" instead of "IPFS Companion"

Makes sense! (Desktop btw 😄)

> "Logs Folder" → "Open Logs"

Agreed!

> "Quit" – will this also shut down the go-ipfs?

Yes, quit everything.

> I think renaming "Connections" to "Backends" will make things more clear

Agreed!

> (perhaps) rename "Repo Path" to IPFS_PATH (to match environment variable)

Not sure if `IPFS_PATH` would be much better. What about 'Ipfs Path' or 'IFPS Path'?

> Those random "pet names" for backends are not user friendly

Yes, they aren't but I believe it is mostly an issue with our current design on this section. And yeah, we can prefix them with the lang.

**Comment by hacdias** [comment]
@ipfs/gui-team following a talk I had with @olizilla in the hack day, we thought about decoupling the Connections window from the menubar and make it open in a separate window with more room to show info to the user. We could eventually decouple all of the settings and make them open on a different window and let the main window be just the entry point to everything.

Talking about that, what should the menubar itself have? Right now, we just show some addresses, if it's connected or not, and a button to open the Web UI.

**Comment by hacdias** [comment]
@olizilla that's just awesome. I really need to investigate how to create that arrow thingy with Electron. I know it's possible but since not all platforms use it (most Windows menubar apps **don't** have the arrow), we could just show it on macOS.

**Comment by olizilla** [comment]
@hacdias the arrow is totally optional! We can figure it out later.

**Comment by patrykadas** [comment]
I was playing around a bit with design as well, thought about highlighting the shared files (Dropbox-like) and delegate everything else to the web application to treat a desktop more like a shortcut and to allow me quick actions around the node.

I am not aware about your design specs nor product decision, so I'd treat it more as an exploration, perhaps you could play with it a bit further.

https://www.figma.com/file/YTMV7cOMmDSfqw8BgwoncbJ5/IPFS-Desktop

**Comment by jessicaschilling** [comment]
Closing this issue - a lot has evolved since it's last been worked, and it's also cross-referenced from a number of currently active issues (so it won't die in isolation).
