### ISSUE TITLE
Renaming WebUI and Station

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-gui#5]
In the last call -- https://github.com/protocol/pm-ipfs-gui/blob/master/meeting-notes/2017-12-14--ipfs-gui-kickoff.md -- we reached a consensus that WebUI needs a new name as it currently is a very misleading name or just not informative at all.

My first proposal is `ipfs-control-room` so that we have a:

- ipfs-station - Docking station on a user machine
- ipfs-control-room - Dashboard for the user to control its station and/or ship
- ipfs-companion (or ipfs-ship !!) - The vessel that takes you through the DWeb

In my head, it makes it a sweet evolution from the era where people **Surfed the Web** to the era where people **Spacetravel the DWeb**!

Other ideas?

**Comment by lidel** [comment]
## Station → IPFS Desktop

Done, Station is now known as IPFS Desktop: https://github.com/ipfs-shipyard/ipfs-desktop ✔️ 

## WebUI → ?

Lars raised some concerns about proposed WebUI names: https://github.com/ipfs-shipyard/ipfs-webui/issues/612#issuecomment-353508706 ✖️ 
Let's continue brainstorming there.

**Comment by olizilla** [comment]
There are no plans to rename Web UI in the near future. It's called `Web UI` for humans and `webui` for machines.
