### ISSUE TITLE
Windows integration (Installer, "Send To", Controller)

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/ipfs-gui#54]
Examples: https://github.com/marcin212/ipfs-gui  
Examples: https://github.com/bogdoslav/ipfs-windows-installer  
Other solutions: https://github.com/Siderus/Orion  
Items needed:
- [ ] Installer and Uninstaller
- [ ] Send To IPFS similar to Email/zip
- [ ] On-off switch and Startup Widget
- [ ] Autostart and TOR/I2P options

**Comment by jessicaschilling** [comment]
Closing (stale); please re-open if needed. Thank you!
