### ISSUE TITLE
Write Permissions

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-gui#58]
@olizilla since this was moved from shipyard I no longer have write permissions to this repository. Could you add me, please? Every time I try to do something on Waffle board, it just shows me a message saying 'Only collaborators can update cards.'.

**Comment by lidel** [comment]
@diasdavid  what is best practice for handling these cases? Adding @hacdias  as a Collaborator to this specific project, or adding him to a group that already has access?

**Comment by diasdavid** [comment]
@lidel do we have a list of folks on the GUI team? I can create that team for you

**Comment by lidel** [comment]
@diasdavid I think list of folks is listed at https://github.com/ipfs/ipfs-gui#team but CCing @olizilla for double-check

**Comment by diasdavid** [comment]
Team created and members added -- https://github.com/orgs/ipfs/teams/gui-team/members --. @lidel @olizilla made you maintainers so that you can add/rm people if you need :)

**Comment by lidel** [comment]
Thank you @diasdavid !
@olizilla I think you have admin rights for this repo, please make sure `@ipfs/gui-team` is on the read-write list :)

**Comment by diasdavid** [comment]
I did both right away, Sir! Who do you think I am? :D 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1211152/42736477-34cdb3b0-8868-11e8-8fbf-ee4ad0189701.png">

**Comment by hacdias** [comment]
Thanks @diasdavid @lidel 😄
