### ISSUE TITLE
IPFS blog GUI?

### ISSUE THREAD

**Issue by miyazono** [ipfs/ipfs-gui#60]
It's time to make a venue for posting content generated by researchers at PL.

I don't think we need a new domain - the most logical place to put this would be https://protocol.ai/research
I don't think we need much design - I want it to be pretty [brutalist](https://brutalist-web.design/)

I think it should be on IPFS
I think it should be user friendly - ideally researchers could preview and post markdown with images without needing to ask for help
I think it should also be useable on the [filecoin blog](https://filecoin.io/blog), [main PL blog](https://protocol.ai/blog/), and perhaps even the [IPFS "starlog" blog](https://ipfs.io/blog/)

Perhaps most importantly, this effort ideally should not cause a noticeable slow down other IPFS projects - this likely means bringing in an external individual or team.

@olizilla, any recommendations?

**Comment by olizilla** [comment]
All the other blogs listed are built on [hugo](http://gohugo.io/), and it delivers on the requirement for ingesting markdown and outputting a static site that can be hosted on IPFS.

It's templating system assumes some familairity with Go, and we are looking to a replacement https://github.com/ipfs/docs/issues/71 but for a simple blog, it'll work great, and you could probably roll it out yourself with an off the peg theme https://themes.gohugo.io/ to get things started.

**Comment by miyazono** [comment]
Thank you!  That's really helpful info, but I think you're overestimating either my prowess or the amount of bandwidth I'd be willing to spend on this (or both).  I hate to say it, but at this time, I'm far more interested in a result than a learning experience.  If it seems too trivial to bring in a contractor for, is there anyone already in the PL family whom I could ask to do this in return for a generously proportional favor?  Or if bringing in someone is the way to do things right, is there anyone you can think of?

**Comment by jessicaschilling** [comment]
Closing since we have a beautiful research website now!
