### ISSUE TITLE
Reading list

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#61]
This is a place for references and good reads to help us get the human-centred design process right. 

- https://blog.coinbase.com/why-design-is-the-killer-app-for-crypto-dcb00d2b1fa6  Call to action for human-centred design for crytpography
- https://www.bbc.co.uk/gel/articles/about-bbc-uxd The BBCs intro to their UX team

#### Design systems

Every one has a "design system" library page now. I'm not convinced we need to add another one to the world, but we do want to capture some common patterns and UI controls in a way that will save developers some time and effort when building new IPFS apps and have good a11y and useability ideas baked in

- https://design.firefox.com/photon/welcome.html - moz's design process is something we should learn from.
- https://www.bbc.co.uk/gel/guidelines/category/design-patterns - the bbc has a strong remit to design for the public good. So do we.
- https://design-system.service.gov.uk
- http://atlaskit.atlassian.com - slick.
- http://www.carbondesignsystem.com - also fancy.
- http://tachyons.io - a design system without the ceremony. Defined scales and palettes that work well together, without dictating a look and feel.

and much more...

**Comment by olizilla** [comment]
https://medium.com/offline-camp/ux/home The UX challenges of offline-first apps are similar to those of p2p systems.

**Comment by fsdiogo** [comment]
* [atomicdesign.bradfrost.com](http://atomicdesign.bradfrost.com/table-of-contents/)

**Comment by olizilla** [comment]
https://blog.coinbase.com/why-design-is-the-killer-app-for-crypto-dcb00d2b1fa6

**Comment by jessicaschilling** [comment]
Closing issue - migrated all of these links into the Further Reading page of the design methods toolbox in the PL Handbook. https://app.gitbook.com/@protocol-labs/s/handbook/design/toolbox/further-reading
