### ISSUE TITLE
User testing - check our assumptions and iterate based on user feedback.

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#62]
We want a virtuous cycle of design -> build -> test -> repeat. We want good user feedback that helps inform our design choices.

We need to define our goals for the apps and the set of tasks that a user should be able to perform without assistance.

TODO:  Define the tasks that each app should make easy, and those it should make possible as a user test plan. (we can't make every feature equally obvious... or nothing is obvious)

- [ ] webui user test plan - https://github.com/ipfs-shipyard/ipfs-webui/issues/746
- [ ] companion user test plan
- [ ] desktop user test plan

**Comment by ericronne** [comment]
cc @jessicaschilling ([soon to be added to this repo](https://github.com/ipfs/ipfs-gui/issues/81))

**Comment by jessicaschilling** [comment]
We're baking user testing into this process as a whole, so closing this issue 😊
