### ISSUE TITLE
Permissions and Repos

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-gui#64]
There are some issues around the permissions on IPFS Shipyard GUI team.

@VictorBjelkholm could you add https://github.com/ipfs-shipyard/ipfs-share-files to GUI Team and then add us Admin or, at least, Write permission to all repositories listed here:

https://github.com/orgs/ipfs-shipyard/teams/gui/repositories

Thankkks 😄

**Comment by hacdias** [comment]
Ping @ipfs/infrastructure

**Comment by lgierth** [comment]
Hey hey I added the admin, ci, and gui teams, and removed the individual user permissions

**Comment by hacdias** [comment]
@lgierth thanks. Could you also go over this list of repos: https://github.com/orgs/ipfs-shipyard/teams/gui/repositories and do the same, please? 😄

**Comment by lgierth** [comment]
sure - done

**Comment by hacdias** [comment]
Thank you 😄
