### ISSUE TITLE
Define our browserlist. Which browser dont we support and why?

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#66]
The main question here is, what browsers can we support, and what browser should we support. For web apps that use an embedded `js-ipfs` instance, the bar is high, it needs modern features, but we should document those, so we can figure out the right browserslist for it.

For web apps that don't intend to use `js-ipfs` we should aim to be as inclusive as possible. `js-ipfs-api` makes http requests to a remote ipfs node, so there is no strong reason why we can't support older browsers beyond the time and effort it takes. It's worth remembering that people running older browsers aren't doing so to deliberately make developers lives harder, but because they are not allowed or can't afford the time, money, or energy to do so.

From https://github.com/ipfs-shipyard/ipld-explorer/pull/37#discussion_r215810050

The current defaults config for `browserslist` is:

* `defaults`: Browserslist’s default browsers
  (`> 0.5%, last 2 versions, Firefox ESR, not dead`).

where `dead` is defined as:

* `dead`: browsers from `last 2 version` query, but with less than 0.5%
  in global usage statistics and without official support or updates
  for 24 months. Right now it is `IE 10`, `IE_Mob 10`, `BlackBerry 10`,
  `BlackBerry 7`, and `OperaMobile 12.1`.

The default setting currently includes the following browsers:

```console
$ npx browserslist@latest "defaults"
npx: installed 5 in 2.489s
and_chr 67
and_ff 60
and_qq 1.2
and_uc 11.8
android 67
android 4.4.3-4.4.4
android 4.4
baidu 7.12
chrome 68
chrome 67
chrome 66
chrome 63
chrome 49
edge 17
edge 16
firefox 61
firefox 60
ie 11
ie_mob 11
ios_saf 11.3-11.4
ios_saf 11.0-11.2
ios_saf 10.3
op_mini all
op_mob 46
opera 55
opera 54
safari 11.1
safari 11
samsung 7.2
samsung 6.2
samsung 4
```

**Comment by lidel** [comment]
Additional data point: [random things break](https://github.com/search?q=%22Please+use+a+browser+with+webcrypto+support%22&type=Issues) without access to [WebCrypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API), which is only available in [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).
We can remove support for browsers without those.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/community/issues/393
