### ISSUE TITLE
Objectives for Q4 2018

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#67]
Q4 2018 OKRs - A.K.A. _What the @ipfs/gui-team are going to focus on over the next 3 months._

## Core IPFS features are intuitive and accessible to all

- [ ] On board a full time UI/UX designer
- [ ] IPFS Desktop v2.0 is released reusing components from Web UI
- [ ] IPFS Desktop has a signed installer for Windows, OSX and Linux, with auto-updating enabled by default.
- [ ] share.ipfs.io is shipped in Web UI, Desktop and Companion
- [ ] Web UI has a stable monthly release with fixes and new translations
- [ ] Web UI has a useability test plan and 5 recorded testing sessions
- [ ] Published blog posts and video explainers for Web UI and Desktop, and docs.ipfs.io recommends installing Desktop
- [ ] Web UI works with IPFS cluster and show cluster specific information.

## Developers are empowered to make great new IPFS user interfaces

- [ ] There is a published UI cookbook with components and documented common api usage patterns.
- [ ] The Web UI File Browser is extracted as a standalone components that can be re-used on the gateway and other web apps.

## The GUIs push forward understanding and adoption of IPFS

- [ ] Web UI visualises DHT and bitswap and helps developers optimise the internals.
- [ ] Pin buddy system allows friends to form ad-hoc IPFS clusters - #36

**Comment by olizilla** [comment]
This list gets frozen on Wednesday 26th. Feedback is welcome!

**Comment by hsanjuan** [comment]
>  Pin buddy system allows friends to form ad-hoc IPFS clusters - #36

So happy to see this here. We (cluster) have allocated time to work on this during this quarter but I'm not sure we will get it to a usable state, so you may want to de-prioritize this one.

>  Web UI works with ipfs-cluster and shows cluster specific information

Yes! I'm going to put this in our OKRs too to make sure we can implement anything you need on our side.

**Comment by olizilla** [comment]
> 2-3 minutes on Q3 scoring / review.  Please focus on your high priority items, what you shipped, and learnings.

- https://explore.ipld.io
- https://proto.school
- https://share.ipfs.io
- https://webui.ipfs.io
- https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.5.1

** Learnings**
- We deviated from the OKRs to better support people going to dweb, but that got us ipld explorer and proto.school
- We didnt do a time budget and significantly over estimated how much we'd fit in a quarter
- I've seen that "coding harder" ultimately doesn't help deliver things faster when I'm supposed to be project managing.
- Mid 3Q retrospective https://github.com/ipfs/ipfs-gui/issues/63
- End 3Q retrospective https://docs.google.com/document/d/1fXFUntQrOb5HYDP0jMlKTQ4SC014tWwam3pfGojMiFY/edit

> 5-10 minutes on Q4 OKRs.  For each major objective please speak to the “why” and call out any cross team/wg dependencies.

- go-ipfs: Error in adding files over HTTP API is causing us pain  https://github.com/ipfs/go-ipfs/issues/5168
