### ISSUE TITLE
Self-hosted analytics for our apps

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#72]
Analytics and usage metrics would show us what features of our apps are getting used and which are not. This would help us make better decisions on what areas need more work.

Agregating usage analytics works well as a centralised service. We can set up our own self-hosted analytics server for the job, rather than relying on 3rd parties, and we can ensure that our apps inform the user about the data that is being captured and why.

Existing self-hosted analytics solutions to research
- https://count.ly/
- https://usefathom.com/
- http://www.openwebanalytics.com/
- https://matomo.org/ (formerly piwik)

**Comment by olizilla** [comment]
https://riot.im uses a banner to announce the analytics to the user and it is opt-in

<img width="1552" alt="screenshot 2018-12-07 at 11 28 35" src="https://user-images.githubusercontent.com/58871/50230451-9a508980-03a4-11e9-876f-26a30040f3c8.png">

There is a link that shows you what data is captured too

<img width="1552" alt="screenshot 2018-12-07 at 11 29 20" src="https://user-images.githubusercontent.com/58871/50230491-a9373c00-03a4-11e9-9c3e-22c61ccd4f4c.png">

**Comment by cobyalmond** [comment]
Hi @olizilla I've been following the larger project since it was announced and I'd like to contribute toward this aspect, if I can.

**Comment by SgtPooki** [comment]
cleaning up old issue. we're using countly for now though we may switch to plausible.io in the future.
