### ISSUE TITLE
Adding folder to IPFS through GUI always fails for me

### ISSUE THREAD

**Issue by Gozala** [ipfs/ipfs-gui#73]
I'm accessing GUI through companion extension. It appears to be `Revision 71e8688` and Version appears as `go-ipfs v0.4.18`

Navigating to "Files" `moz-extension://38a3b00c-8421-ee4d-a6cc-4f4a0ef09ab3/webui/index.html#/files/` clicking `+ Add files` then `Add folder` lets me choose a directory but fails every time with a following message displayed at the bottom.

<img width="441" alt="screen shot 2018-12-28 at 12 21 45 pm" src="https://user-images.githubusercontent.com/21236/50527147-53951a80-0a9b-11e9-966d-39ef0709294b.png">

**Comment by olizilla** [comment]
Fixed in https://github.com/ipfs-shipyard/ipfs-webui/pull/931
