### ISSUE TITLE
IPFS color palette

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#74]
The IPFS color palette in a bunch of formats

- **Sketch:** https://drive.google.com/open?id=1uWzwWbueZtHQBkSz093XHGVOuOmAffFq
- **JSON:** https://github.com/ipfs-shipyard/ipfs-css/blob/master/theme.json#L2
- **CSS:** https://github.com/ipfs-shipyard/ipfs-css/blob/master/src/theme.css#L8

_the css is derived from the JSON definition_

## Swatches <small></small>

<img title='#0b3a53' src='https://swatches.now.sh?color=%230b3a53&name=navy' /><img title='#244e66' src='https://swatches.now.sh?color=%23244e66&name=navy-muted' /><img title='#69c4cd' src='https://swatches.now.sh?color=%2369c4cd&name=aqua' /><img title='#9ad4db' src='https://swatches.now.sh?color=%239ad4db&name=aqua-muted' />

<img title='#b7bbc8' src='https://swatches.now.sh?color=%23b7bbc8&name=gray' /><img title='#d9dbe2' src='https://swatches.now.sh?color=%23d9dbe2&name=gray-muted' /><img title='#34373f' src='https://swatches.now.sh?color=%2334373f&name=charcoal' /><img title='#7f8491' src='https://swatches.now.sh?color=%237f8491&name=charcoal-muted' />

<img title='#ea5037' src='https://swatches.now.sh?color=%23ea5037&name=red' /><img title='#f36149' src='https://swatches.now.sh?color=%23f36149&name=red-muted' /><img title='#f39021' src='https://swatches.now.sh?color=%23f39021&name=yellow' /><img title='#f9a13e' src='https://swatches.now.sh?color=%23f9a13e&name=yellow-muted' />

<img title='#3e9096' src='https://swatches.now.sh?color=%233e9096&name=teal' /><img title='#439a9d' src='https://swatches.now.sh?color=%23439a9d&name=teal-muted' /><img title='#0cb892' src='https://swatches.now.sh?color=%230cb892&name=green' /><img title='#0aca9f' src='https://swatches.now.sh?color=%230aca9f&name=green-muted' />

<img title='#edf0f4' src='https://swatches.now.sh?color=%23edf0f4&name=snow' /><img title='#f7f8fa' src='https://swatches.now.sh?color=%23f7f8fa&name=snow-muted' />

via https://github.com/olizilla/swatches  on https://swatches.now.sh

**Comment by jessicaschilling** [comment]
Closing; migrated to a .md in the repo's main directory. This is likely temporary; eventually it'll be part of a larger brand guide effort.
