### ISSUE TITLE
Animation while Adding Peer Connection

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs/ipfs-gui#90]
In the Peers screen, the "Add connection" can take a considerable amount of time. So, to entertain the user and provide feedback, we should add a rich animation.

Jessica gave a cool idea, that would be something a constellation/mesh turning into the IPFS cube.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 Thanks for getting this into the issues! Let's keep it low on overall priorities, but it would be super cool to have at some point - and could scale to other areas where we could benefit from animation.
